In [1]:
import inventorize

In [2]:
prime_numbers=[1,3,5,7,11,13,17]

In [3]:
prime_numbers=2

In [4]:
prime_numbers=[1,3,5,7,11,13,17]

In [5]:
prime_numbers=[2]

In [6]:
prime_numbers=[1,3,5,7,11,13,17]

In [7]:
prime_numbers[3]

7

In [8]:
prime_numbers[:5]

[1, 3, 5, 7, 11]

In [9]:
prime_numbers[3:]

[7, 11, 13, 17]

In [10]:
prime_numbers=[1,3,5,7,11,13,17]

In [11]:
prime_numbers[3:]

[7, 11, 13, 17]

In [13]:
Products_list=['Shampoo','hair oil','face masks',"lip balm","lipstick","talc"]

In [14]:
Products_list[4]

'lipstick'

In [18]:
class_dict={'Pranay':'Male','Aman':'Male','Nayanshi':'Female','Sanjay':'Male','Poonam': 'Female'}

In [19]:
class_dict

{'Pranay': 'Male',
 'Aman': 'Male',
 'Nayanshi': 'Female',
 'Sanjay': 'Male',
 'Poonam': 'Female'}

In [20]:
class_dict.keys()

dict_keys(['Pranay', 'Aman', 'Nayanshi', 'Sanjay', 'Poonam'])

In [21]:
class_dict.values()

dict_values(['Male', 'Male', 'Female', 'Male', 'Female'])

In [22]:
class_dict['Pranay']

'Male'

In [26]:
class_dict['Aman']

'Male'

In [28]:
class_dict.get('Aman')

'Male'

In [29]:
import pandas as pd

In [30]:
demo_data=pd.read_csv('pakistan_economic_indicators_2000_2025.csv')

In [31]:
demo_data

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,12.3,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,34.5,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,55.1,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,58.3,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,57.7,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,61.3,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,65.5,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,72.6,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,71.2,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,73.2,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,72.3,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,69.7,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,72.1,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,77.2,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,76.0,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,80.0,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [32]:
demo_data.head()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
0,2000,99.9,3.9,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0.3,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s
1,2001,101.4,2.0,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0.6,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s
2,2002,107.6,3.1,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,1.8,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s
3,2003,116.3,4.7,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,3.3,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s
4,2004,126.7,7.4,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,7.7,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s

In [33]:
demo_data.tail()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,mobile_per_100,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,82.4,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,82.6,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,84.0,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,85.5,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,87.0,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s

In [34]:
demo_data.shape

(26, 32)

In [35]:
demo_data.describe()

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,agriculture_gdp_pct,services_gdp_pct,industry_gdp_pct,tax_revenue_gdp_pct,mobile_per_100,imf_program_active,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct
count,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,...,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000,26.000000
mean,2012.500000,233.084615,4.110000,1012.153846,9.361538,6.261538,14.866538,21.453846,39.853846,-18.400000,...,22.438462,51.834615,25.726923,11.273077,55.546154,0.423077,5.504231,9.543077,16.530769,0.976538
std,7.648529,92.279119,2.195969,258.434161,6.431739,1.059085,10.775681,6.914809,18.568494,12.195934,...,1.303557,1.909543,0.944270,1.422549,30.772471,0.503831,2.481398,1.360852,3.465463,0.807802
min,2000.000000,99.900000,-0.500000,614.000000,2.900000,4.500000,1.080000,9.200000,10.300000,-47.600000,...,20.900000,47.200000,24.300000,9.100000,0.300000,0.000000,1.080000,7.210000,10.130000,0.310000
25%,2006.250000,156.300000,2.700000,807.000000,4.650000,5.650000,5.375000,17.775000,29.075000,-22.775000,...,21.500000,51.175000,25.025000,10.225000,39.650000,0.000000,3.370000,8.515000,14.877500,0.510000
50%,2012.500000,243.350000,4.100000,1040.500000,7.750000,6.000000,13.555000,22.000000,44.100000,-20.250000,...,22.400000,52.300000,25.650000,10.850000,70.450000,0.000000,5.570000,9.285000,16.985000,0.745000
75%,2018.750000,299.375000,5.650000,1226.000000,11.200000,6.475000,21.935000,24.800000,48.475000,-11.300000,...,22.900000,53.075000,26.350000,12.350000,76.900000,1.000000,7.112500,10.555000,19.205000,0.955000
max,2025.000000,390.000000,9.000000,1393.000000,29.200000,8.300000,38.000000,34.000000,80.000000,-0.500000,...,26.000000,54.100000,27.700000,14.500000,87.000000,1.000000,9.740000,12.200000,21.250000,3.330000

In [38]:
demo_data.unemployment_pct.describe()

count    26.000000
mean      6.261538
std       1.059085
min       4.500000
25%       5.650000
50%       6.000000
75%       6.475000
max       8.300000
Name: unemployment_pct, dtype: float64

In [39]:
demo_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    26 non-null     int64
 1   gdp_usd_bn              26 non-null     float64
 2   gdp_growth_pct          26 non-null     float64
 3   gdp_per_capita_usd      26 non-null     int64
 4   inflation_cpi_pct       26 non-null     float64
 5   unemployment_pct        26 non-null     float64
 6   remittances_usd_bn      26 non-null     float64
 7   exports_usd_bn          26 non-null     float64
 8   imports_usd_bn          26 non-null     float64
 9   trade_balance_usd_bn    26 non-null     float64
 10  forex_reserves_usd_bn   26 non-null     float64
 11  policy_rate_pct         26 non-null     float64
 12  pkr_per_usd             26 non-null     float64
 13  public_debt_gdp_pct     26 non-null     float64
 14  current_account_usd_bn  26 non-null     float64
 15  fdi_inflows_usd_bn      26 non-null     float64
 16  population_mn           26 non-null     float64
 17  literacy_rate_pct       26 non-null     float64
 18  agriculture_gdp_pct     26 non-null     float64
 19  services_gdp_pct        26 non-null     float64
 20  industry_gdp_pct        26 non-null     float64
 21  tax_revenue_gdp_pct     26 non-null     float64
 22  mobile_per_100          26 non-null     float64
 23  imf_program_active      26 non-null     int64
 24  key_events              26 non-null     str
 25  remittances_gdp_pct     26 non-null     float64
 26  exports_gdp_pct         26 non-null     float64
 27  imports_gdp_pct         26 non-null     float64
 28  fdi_gdp_pct             26 non-null     float64
 29  gdp_growth_category     26 non-null     str
 30  inflation_category      26 non-null     str
 31  decade                  26 non-null     str
dtypes: float64(25), int64(3), str(4)
memory usage: 6.6 KB

In [46]:
first_five=demo_data.iloc[1:5,1:5]

In [48]:
first_five

   gdp_usd_bn  gdp_growth_pct  gdp_per_capita_usd  inflation_cpi_pct
1       101.4             2.0                 614                3.1
2       107.6             3.1                 628                3.5
3       116.3             4.7                 657                3.1
4       126.7             7.4                 697                7.4

In [51]:
two_column= demo_data.loc[:,['gdp_usd_bn','gdp_per_capita_usd']]
two_column

    gdp_usd_bn  gdp_per_capita_usd
0         99.9                 624
1        101.4                 614
2        107.6                 628
3        116.3                 657
4        126.7                 697
5        137.4                 736
6        152.4                 795
7        168.0                 855
8        192.5                 956
9        173.6                 843
10       177.1                 843
11       222.2                1043
12       239.6                1097
13       247.1                1109
14       270.6                1193
15       271.1                1168
16       282.5                1190
17       305.0                1258
18       314.6                1268
19       263.7                1038
20       263.2                1016
21       348.7                1315
22       376.5                1393
23       337.9                1237
24       374.6                1353
25       390.0                1390

In [52]:
second_subset= demo_data.iloc[[1,2,3],[1,2,3]]
second_subset

   gdp_usd_bn  gdp_growth_pct  gdp_per_capita_usd
1       101.4             2.0                 614
2       107.6             3.1                 628
3       116.3             4.7                 657

In [53]:
demo_data.columns

Index(['year', 'gdp_usd_bn', 'gdp_growth_pct', 'gdp_per_capita_usd',
       'inflation_cpi_pct', 'unemployment_pct', 'remittances_usd_bn',
       'exports_usd_bn', 'imports_usd_bn', 'trade_balance_usd_bn',
       'forex_reserves_usd_bn', 'policy_rate_pct', 'pkr_per_usd',
       'public_debt_gdp_pct', 'current_account_usd_bn', 'fdi_inflows_usd_bn',
       'population_mn', 'literacy_rate_pct', 'agriculture_gdp_pct',
       'services_gdp_pct', 'industry_gdp_pct', 'tax_revenue_gdp_pct',
       'mobile_per_100', 'imf_program_active', 'key_events',
       'remittances_gdp_pct', 'exports_gdp_pct', 'imports_gdp_pct',
       'fdi_gdp_pct', 'gdp_growth_category', 'inflation_category', 'decade'],
      dtype='str')

In [56]:
demo_data['Demo_class']= demo_data['gdp_growth_pct']*10

In [58]:
demo_data

,year,gdp_usd_bn,gdp_growth_pct,gdp_per_capita_usd,inflation_cpi_pct,unemployment_pct,remittances_usd_bn,exports_usd_bn,imports_usd_bn,trade_balance_usd_bn,...,imf_program_active,key_events,remittances_gdp_pct,exports_gdp_pct,imports_gdp_pct,fdi_gdp_pct,gdp_growth_category,inflation_category,decade,Demo_class
0,2000,99.9,3.90,624,4.4,7.8,1.08,9.2,10.3,-1.1,...,0,Post-sanctions recovery,1.08,9.21,10.31,0.31,Moderate Growth,Low,2000s,39.0
1,2001,101.4,2.00,614,3.1,7.8,1.46,9.8,10.3,-0.5,...,0,9/11 impact + debt relief,1.44,9.66,10.16,0.37,Low Growth,Low,2000s,20.0
2,2002,107.6,3.10,628,3.5,8.3,2.39,10.0,10.9,-0.9,...,0,Economic reform start,2.22,9.29,10.13,0.76,Moderate Growth,Low,2000s,31.0
3,2003,116.3,4.70,657,3.1,8.3,3.96,11.7,12.2,-0.5,...,0,Growth acceleration,3.40,10.06,10.49,0.46,Moderate Growth,Low,2000s,47.0
4,2004,126.7,7.40,697,7.4,7.7,3.87,14.0,15.5,-1.5,...,0,High growth period,3.05,11.05,12.23,0.88,High Growth,Moderate,2000s,74.0
5,2005,137.4,9.00,736,9.3,7.7,4.28,16.5,25.4,-8.9,...,0,Record growth 8.6%,3.11,12.01,18.49,1.60,High Growth,Moderate,2000s,90.0
6,2006,152.4,5.80,795,7.9,6.2,5.12,18.6,30.5,-11.9,...,0,Growth slowdown,3.36,12.20,20.01,2.80,Moderate Growth,Moderate,2000s,58.0
7,2007,168.0,6.80,855,7.6,5.2,6.14,17.5,28.6,-11.1,...,1,Global commodity boom,3.65,10.42,17.02,3.33,High Growth,Moderate,2000s,68.0
8,2008,192.5,5.00,956,12.0,5.2,6.45,20.4,39.9,-19.5,...,0,Global financial crisis,3.35,10.60,20.73,2.83,Moderate Growth,High,2000s,50.0
9,2009,173.6,2.60,843,20.8,5.5,7.81,19.6,31.7,-12.1,...,1,IMF bailout + floods,4.50,11.29,18.26,1.35,Low Growth,Hyperinflationary,2000s,26.0
10,2010,177.1,1.60,843,11.7,5.6,8.91,19.3,34.7,-15.4,...,0,Floods recovery,5.03,10.90,19.59,1.14,Low Growth,High,2010s,16.0
11,2011,222.2,3.60,1043,13.7,6.0,11.20,24.8,43.6,-18.8,...,1,Debt restructuring,5.04,11.16,19.62,0.73,Moderate Growth,High,2010s,36.0
12,2012,239.6,4.40,1097,9.7,6.0,13.19,24.0,44.9,-20.9,...,1,IMF program + energy crisis,5.51,10.02,18.74,0.36,Moderate Growth,Moderate,2010s,44.0
13,2013,247.1,3.70,1109,7.4,6.2,13.92,24.7,45.1,-20.4,...,0,Political transition,5.63,10.00,18.25,0.54,Moderate Growth,Moderate,2010s,37.0
14,2014,270.6,4.10,1193,8.6,6.0,15.84,25.1,47.5,-22.4,...,0,CPEC launch,5.85,9.28,17.55,0.60,Moderate Growth,Moderate,2010s,41.0
15,2015,271.1,4.10,1168,4.5,5.9,18.72,22.0,44.9,-22.9,...,0,Commodity price fall,6.91,8.12,16.56,0.35,Moderate Growth,Low,2010s,41.0
16,2016,282.5,5.50,1190,2.9,5.9,19.31,22.0,42.1,-20.1,...,0,Growth recovery,6.84,7.79,14.90,0.91,Moderate Growth,Low,2010s,55.0
17,2017,305.0,5.20,1258,4.2,5.8,19.68,22.0,48.8,-26.8,...,1,CPEC investment peak,6.45,7.21,16.00,0.82,Moderate Growth,Low,2010s,52.0
18,2018,314.6,5.80,1268,5.1,5.8,21.02,24.8,60.9,-36.1,...,1,Twin deficits crisis,6.68,7.88,19.36,0.90,Moderate Growth,Moderate,2010s,58.0
19,2019,263.7,1.90,1038,6.7,4.5,22.24,22.5,44.6,-22.1,...,0,IMF stabilization,8.43,8.53,16.91,0.84,Low Growth,Moderate,2010s,19.0
20,2020,263.2,-0.50,1016,8.9,4.6,23.12,22.4,44.6,-22.2,...,1,COVID-19 pandemic,8.78,8.51,16.95,0.97,Recession/Negative,Moderate,2020s,-5.0
21,2021,348.7,5.70,1315,8.9,6.3,31.10,31.8,72.7,-40.9,...,1,Post-COVID rebound,8.92,9.12,20.85,0.52,Moderate Growth,Moderate,2020s,57.0
22,2022,376.5,6.10,1393,12.2,6.2,27.02,32.4,80.0,-47.6,...,0,Record inflation + floods,7.18,8.61,21.25,0.51,High Growth,High,2020s,61.0
23,2023,337.9,-0.04,1237,29.2,6.5,26.10,27.7,55.3,-27.6,...,1,IMF bailout + PKR crash,7.72,8.20,16.37,0.44,Recession/Negative,Hyperinflationary,2020s,-0.4
24,2024,374.6,2.40,1353,23.4,6.4,34.60,31.0,53.2,-22.2,...,1,Stabilization + disinflation,9.24,8.28,14.20,0.51,Low Growth,Hyperinflationary,2020s,24.0
25,2025,390.0,3.00,1390,7.2,5.4,38.00,34.0,58.0,-24.0,...,1,Recovery + record remittances,9.74,8.72,14.87,0.56,Low Growth,Moderate,2020s,30.0